# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'TheBlog'
tagline:          'A Metro theme for Jekyll'
description:      '随手记'
url:              '//x20080406.github.io'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
#- text: Resume
#  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/


# Author Details
author:         'x20080406'

#Social Media links
twitter:        'https://twitter.com/x20080406'
facebook:       'https://www.facebook.com/olakara'
gplus:          'https://plus.google.com/100425464897246255887/'

# Google Analytics
gahandler: 'UA-62748280-1'

#if footer-links-visible is 'true' the svg-icons will be shown top on the copy right.
#else the svg icons will not exist
footersvg: 'true'

footer-links:
  dribbble:
  email: None
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  google: None
  twitter: None
  stackoverflow: #users/4388898/peter-zhu # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Disqus
disqushandler: '	'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.8
